// Code generated by protoc-gen-go. DO NOT EDIT.
// source: musiclib.proto

package mlibgrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BrowseType int32

const (
	BrowseType_BROWSE_TYPE_UNSPECIFIED  BrowseType = 0
	BrowseType_BROWSE_TYPE_FOLDER       BrowseType = 1
	BrowseType_BROWSE_TYPE_ALBUM_ARTIST BrowseType = 2
)

var BrowseType_name = map[int32]string{
	0: "BROWSE_TYPE_UNSPECIFIED",
	1: "BROWSE_TYPE_FOLDER",
	2: "BROWSE_TYPE_ALBUM_ARTIST",
}

var BrowseType_value = map[string]int32{
	"BROWSE_TYPE_UNSPECIFIED":  0,
	"BROWSE_TYPE_FOLDER":       1,
	"BROWSE_TYPE_ALBUM_ARTIST": 2,
}

func (x BrowseType) String() string {
	return proto.EnumName(BrowseType_name, int32(x))
}

func (BrowseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7a6d90c975a0c672, []int{0}
}

type BrowseRequest struct {
	Path                 string     `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Search               string     `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	Reverse              bool       `protobuf:"varint,3,opt,name=reverse,proto3" json:"reverse,omitempty"`
	BrowseType           BrowseType `protobuf:"varint,4,opt,name=browse_type,json=browseType,proto3,enum=mlibgrpc.BrowseType" json:"browse_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BrowseRequest) Reset()         { *m = BrowseRequest{} }
func (m *BrowseRequest) String() string { return proto.CompactTextString(m) }
func (*BrowseRequest) ProtoMessage()    {}
func (*BrowseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a6d90c975a0c672, []int{0}
}

func (m *BrowseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrowseRequest.Unmarshal(m, b)
}
func (m *BrowseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrowseRequest.Marshal(b, m, deterministic)
}
func (m *BrowseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrowseRequest.Merge(m, src)
}
func (m *BrowseRequest) XXX_Size() int {
	return xxx_messageInfo_BrowseRequest.Size(m)
}
func (m *BrowseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BrowseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BrowseRequest proto.InternalMessageInfo

func (m *BrowseRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *BrowseRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *BrowseRequest) GetReverse() bool {
	if m != nil {
		return m.Reverse
	}
	return false
}

func (m *BrowseRequest) GetBrowseType() BrowseType {
	if m != nil {
		return m.BrowseType
	}
	return BrowseType_BROWSE_TYPE_UNSPECIFIED
}

type BrowseResponse struct {
	Items                []*BrowseItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BrowseResponse) Reset()         { *m = BrowseResponse{} }
func (m *BrowseResponse) String() string { return proto.CompactTextString(m) }
func (*BrowseResponse) ProtoMessage()    {}
func (*BrowseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a6d90c975a0c672, []int{1}
}

func (m *BrowseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrowseResponse.Unmarshal(m, b)
}
func (m *BrowseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrowseResponse.Marshal(b, m, deterministic)
}
func (m *BrowseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrowseResponse.Merge(m, src)
}
func (m *BrowseResponse) XXX_Size() int {
	return xxx_messageInfo_BrowseResponse.Size(m)
}
func (m *BrowseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BrowseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BrowseResponse proto.InternalMessageInfo

func (m *BrowseResponse) GetItems() []*BrowseItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type BrowseItem struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uri                  string   `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Folder               bool     `protobuf:"varint,3,opt,name=folder,proto3" json:"folder,omitempty"`
	ImageUri             string   `protobuf:"bytes,4,opt,name=image_uri,json=imageUri,proto3" json:"image_uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrowseItem) Reset()         { *m = BrowseItem{} }
func (m *BrowseItem) String() string { return proto.CompactTextString(m) }
func (*BrowseItem) ProtoMessage()    {}
func (*BrowseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a6d90c975a0c672, []int{2}
}

func (m *BrowseItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrowseItem.Unmarshal(m, b)
}
func (m *BrowseItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrowseItem.Marshal(b, m, deterministic)
}
func (m *BrowseItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrowseItem.Merge(m, src)
}
func (m *BrowseItem) XXX_Size() int {
	return xxx_messageInfo_BrowseItem.Size(m)
}
func (m *BrowseItem) XXX_DiscardUnknown() {
	xxx_messageInfo_BrowseItem.DiscardUnknown(m)
}

var xxx_messageInfo_BrowseItem proto.InternalMessageInfo

func (m *BrowseItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BrowseItem) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *BrowseItem) GetFolder() bool {
	if m != nil {
		return m.Folder
	}
	return false
}

func (m *BrowseItem) GetImageUri() string {
	if m != nil {
		return m.ImageUri
	}
	return ""
}

func init() {
	proto.RegisterEnum("mlibgrpc.BrowseType", BrowseType_name, BrowseType_value)
	proto.RegisterType((*BrowseRequest)(nil), "mlibgrpc.BrowseRequest")
	proto.RegisterType((*BrowseResponse)(nil), "mlibgrpc.BrowseResponse")
	proto.RegisterType((*BrowseItem)(nil), "mlibgrpc.BrowseItem")
}

func init() {
	proto.RegisterFile("musiclib.proto", fileDescriptor_7a6d90c975a0c672)
}

var fileDescriptor_7a6d90c975a0c672 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0xc5, 0x40, 0x29, 0x0c, 0x2d, 0xb2, 0x46, 0x15, 0xac, 0x4a, 0x0f, 0x96, 0x4f, 0x16, 0x07,
	0x0e, 0x54, 0xbd, 0x35, 0x07, 0x08, 0x46, 0xb2, 0x04, 0x01, 0x2d, 0x46, 0x51, 0x4e, 0x96, 0x4d,
	0x26, 0xb0, 0x12, 0xc6, 0xce, 0xae, 0x49, 0xc4, 0x7f, 0xc8, 0x8f, 0x8e, 0xfc, 0x95, 0xa0, 0x70,
	0x7b, 0xf3, 0x66, 0x34, 0x6f, 0xde, 0x3c, 0xe8, 0x84, 0x27, 0x25, 0xb6, 0x07, 0x11, 0x0c, 0x63,
	0x19, 0x25, 0x11, 0x36, 0xc3, 0x83, 0x08, 0x76, 0x32, 0xde, 0x9a, 0x6f, 0x1a, 0xfc, 0x9c, 0xc8,
	0xe8, 0x55, 0x11, 0xa7, 0xe7, 0x13, 0xa9, 0x04, 0x11, 0xea, 0xb1, 0x9f, 0xec, 0x99, 0x66, 0x68,
	0x56, 0x8b, 0x67, 0x18, 0xbb, 0xd0, 0x50, 0xe4, 0xcb, 0xed, 0x9e, 0x55, 0x33, 0xb6, 0xa8, 0x90,
	0xc1, 0x77, 0x49, 0x2f, 0x24, 0x15, 0xb1, 0x9a, 0xa1, 0x59, 0x4d, 0x5e, 0x96, 0xf8, 0x0f, 0xda,
	0x41, 0xb6, 0xd6, 0x4b, 0xce, 0x31, 0xb1, 0xba, 0xa1, 0x59, 0x9d, 0xd1, 0xaf, 0x61, 0xa9, 0x3b,
	0xcc, 0x35, 0xdd, 0x73, 0x4c, 0x1c, 0x82, 0x0f, 0x6c, 0xfe, 0x87, 0x4e, 0x79, 0x8d, 0x8a, 0xa3,
	0xa3, 0x22, 0x1c, 0xc0, 0x37, 0x91, 0x50, 0xa8, 0x98, 0x66, 0xd4, 0xac, 0xf6, 0xf5, 0x0a, 0x27,
	0xa1, 0x90, 0xe7, 0x23, 0xe6, 0x0e, 0xe0, 0x93, 0x4c, 0x8d, 0x1c, 0xfd, 0x90, 0x4a, 0x23, 0x29,
	0x46, 0x1d, 0x6a, 0x27, 0x29, 0x0a, 0x17, 0x29, 0x4c, 0xad, 0x3d, 0x45, 0x87, 0x47, 0x92, 0x85,
	0x83, 0xa2, 0xc2, 0x3e, 0xb4, 0x44, 0xe8, 0xef, 0xc8, 0x4b, 0xe7, 0xeb, 0xd9, 0x7c, 0x33, 0x23,
	0x36, 0x52, 0x0c, 0xbc, 0x52, 0x28, 0x3d, 0x1a, 0xfb, 0xd0, 0x9b, 0xf0, 0xe5, 0xfd, 0xda, 0xf6,
	0xdc, 0x87, 0x95, 0xed, 0x6d, 0xee, 0xd6, 0x2b, 0xfb, 0xd6, 0x99, 0x39, 0xf6, 0x54, 0xaf, 0x60,
	0x17, 0xf0, 0xb2, 0x39, 0x5b, 0xce, 0xa7, 0x36, 0xd7, 0x35, 0xfc, 0x03, 0xec, 0x92, 0x1f, 0xcf,
	0x27, 0x9b, 0x85, 0x37, 0xe6, 0xae, 0xb3, 0x76, 0xf5, 0xea, 0x68, 0x01, 0x3f, 0x16, 0x69, 0x64,
	0x73, 0x11, 0x48, 0x5f, 0x9e, 0xf1, 0x06, 0x1a, 0xb9, 0x20, 0xf6, 0xbe, 0x3e, 0xa0, 0xc8, 0xed,
	0x37, 0xbb, 0x6e, 0xe4, 0x2f, 0x34, 0x2b, 0x41, 0x23, 0x8b, 0xfd, 0xef, 0x7b, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x03, 0x1f, 0xcf, 0x73, 0x08, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MusicLibraryClient is the client API for MusicLibrary service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MusicLibraryClient interface {
	Browse(ctx context.Context, in *BrowseRequest, opts ...grpc.CallOption) (*BrowseResponse, error)
}

type musicLibraryClient struct {
	cc grpc.ClientConnInterface
}

func NewMusicLibraryClient(cc grpc.ClientConnInterface) MusicLibraryClient {
	return &musicLibraryClient{cc}
}

func (c *musicLibraryClient) Browse(ctx context.Context, in *BrowseRequest, opts ...grpc.CallOption) (*BrowseResponse, error) {
	out := new(BrowseResponse)
	err := c.cc.Invoke(ctx, "/mlibgrpc.MusicLibrary/Browse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MusicLibraryServer is the server API for MusicLibrary service.
type MusicLibraryServer interface {
	Browse(context.Context, *BrowseRequest) (*BrowseResponse, error)
}

// UnimplementedMusicLibraryServer can be embedded to have forward compatible implementations.
type UnimplementedMusicLibraryServer struct {
}

func (*UnimplementedMusicLibraryServer) Browse(ctx context.Context, req *BrowseRequest) (*BrowseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Browse not implemented")
}

func RegisterMusicLibraryServer(s *grpc.Server, srv MusicLibraryServer) {
	s.RegisterService(&_MusicLibrary_serviceDesc, srv)
}

func _MusicLibrary_Browse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrowseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicLibraryServer).Browse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mlibgrpc.MusicLibrary/Browse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicLibraryServer).Browse(ctx, req.(*BrowseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MusicLibrary_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mlibgrpc.MusicLibrary",
	HandlerType: (*MusicLibraryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Browse",
			Handler:    _MusicLibrary_Browse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "musiclib.proto",
}
